# Generated by Django 4.1.1 on 2022-10-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("Latitude", models.BooleanField()),
                ("Longitude", models.BooleanField()),
                ("Temperature", models.BooleanField()),
                ("Humidity", models.BooleanField()),
                ("Pression", models.BooleanField()),
                ("PM25", models.BooleanField()),
                ("PM10", models.BooleanField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
