# Generated by Django 4.1.2 on 2022-10-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("idSensor", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                (
                    "Latitude",
                    models.DecimalField(decimal_places=7, default=0, max_digits=10),
                ),
                (
                    "Longitude",
                    models.DecimalField(decimal_places=7, default=0, max_digits=10),
                ),
                ("Temperature", models.BooleanField()),
                ("Humidity", models.BooleanField()),
                ("Pression", models.BooleanField()),
                ("PM25", models.BooleanField()),
                ("PM10", models.BooleanField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
