# Generated by Django 4.1.2 on 2022-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="Latitude",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="Longitude",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
