# Generated by Django 4.1.1 on 2022-10-05 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurementDateTime", models.DateTimeField()),
                (
                    "Latitude",
                    models.DecimalField(decimal_places=5, default=0, max_digits=8),
                ),
                (
                    "Longitude",
                    models.DecimalField(decimal_places=5, default=0, max_digits=8),
                ),
                (
                    "Temperature",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "Humidity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "Pression",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "PM25",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "PM10",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
