# Generated by Django 4.1.1 on 2022-10-09 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasensors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasensor",
            name="measurementDateTime",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="sensor",
        ),
        migrations.AddField(
            model_name="datasensor",
            name="measurementDate",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="measurementTime",
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="name",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
