# Generated by Django 4.1.1 on 2022-10-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datasensors", "0002_remove_datasensor_measurementdatetime_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasensor",
            options={
                "ordering": ["id"],
                "verbose_name": "DataSensor",
                "verbose_name_plural": "DataSensors",
            },
        ),
    ]
