# Generated by Django 4.1.1 on 2022-10-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datasensors", "0003_alter_datasensor_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasensor",
            name="Humidity",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="Latitude",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="Longitude",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="PM10",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="PM25",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="Pression",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="Temperature",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="measurementDate",
        ),
        migrations.RemoveField(
            model_name="datasensor",
            name="measurementTime",
        ),
    ]
