# Generated by Django 4.1.1 on 2022-10-09 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasensors", "0004_remove_datasensor_humidity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasensor",
            name="Humidity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="Latitude",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="Longitude",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="PM10",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="PM25",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="Pression",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="Temperature",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="measurementDate",
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="datasensor",
            name="measurementTime",
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
