# Generated by Django 4.1.2 on 2022-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurements",
            name="Latitude",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="measurements",
            name="Longitude",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
